# Site settings
theme: jekyll-theme-cayman
title: Camp Kesem at Duke University Website
author:
  name: Lauren Walker
  email: lgwalker2002@gmail.com
description: "Camp Kesem at Duke University Website"
homepage: https://laurenwalker25.github.io/
