# Site settings
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
title: Camp Kesem at Duke University Website
author:
  name: Lauren Walker
  email: lgwalker2002@gmail.com
description: "Camp Kesem at Duke University Website"
homepage: https://laurenwalker25.github.io/
