# Site settings
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
title: Camp Kesem at Duke University
author:
  name: Lauren Walker
  email: lgwalker2002@gmail.com
description: "A child's friend through and beyond a parent's cancer"
homepage: https://laurenwalker25.github.io/
